### ISSUE TITLE
Seismic Sensor

### ISSUE THREAD

**Issue by benkopiec** [SmartRocksProject/meshtastic-firmware-custom#5]
Verify and demonstrate that seismic sensor works properly and shows correct data.

**Comment by brianglaser** [comment]
1) Turn on ESP 32 board
2) Enable pins associated with SM24 geophone
3) Verify data is being sampled through the terminal
4) Leave geophone stationary in a very calm environment.
5) Have humans walk 20 meters away from the geophone.
6) Verify the appropriate response of data in the terminal.

**Comment by beewyka819** [comment]
Created branch for geophone code

**Comment by beewyka819** [comment]
Geophone sampling and analysis complete and functional.
